"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [navbar, setNavbar] = useState(false);

  return (
    <html lang="en">
      <body>

        <div className="back"> 

          <nav className="w-full fixed top-0 left-0 right-0 z-10">
            <div className="justify-between mx-auto lg:max-w-7xl md:items-center md:flex md:px-8">
              <div>
                <div className="flex items-center justify-between py-4 md:py-5 px-4 md:block ">
                  {/* LOGO */}
                  <Link href="/">
                    <div className="text-xs">
                      <img className="w-20 h-93" src="./logo.svg" alt="logo" />
                    </div>
                  </Link>
                  {/* HAMBURGER BUTTON FOR MOBILE */}
                  <div className="md:hidden relative bottom-3">
                    <button
                      className=" text-gray-700 rounded-md outline-none focus:border-gray-400"
                      onClick={() => setNavbar(!navbar)}
                    >
                      {navbar ? (
                        <svg
                          class="h-8 w-8 text-black"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          stroke-width="2"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        >
                          {" "}
                          <line x1="3" y1="12" x2="21" y2="12" />{" "}
                          <line x1="3" y1="6" x2="21" y2="6" />{" "}
                          <line x1="3" y1="18" x2="21" y2="18" />
                        </svg>
                      ) : (
                        <svg
                          class="w-5 h-4 text-gray-800 dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 17 14"
                        >
                          <path
                            stroke="currentColor"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M1 1h15M1 7h15M1 13h15"
                          />
                        </svg>
                      )}
                    </button>
                  </div>
                </div>
              </div>

              <div>
                <div
                  className={`flex-1 justify-self-center pb-3 mt-8 md:block md:pb-0 md:mt-0 ${
                    navbar ? "p-12 md:p-0 block" : "hidden"
                  }`}
                >
                  <ul className="h-screen md:h-auto items-center justify-center md:flex ">
                    <li className="pb-6 text-xl text-white py-2 md:px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Help
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Dictionaries
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Project
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Mobile App
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Contact us
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>

          {children}

          <footer className="absolute bottom-0 py-5 px-2 w-full">
            <div className="flex justify-between">
              <div className="flex">
                <div>
                  <img
                    className="w-7 h-93"
                    src="./playstore.svg"
                    alt="playstore_logo"
                  />
                </div>
                <div className="pl-8">
                  <img
                    className="w-5 h-93"
                    src="./apple.svg"
                    alt="apple_logo"
                  />
                </div>
              </div>

              <div className="flex">
                <span className="text-white px-3 text-sm">by</span>
                <a href="#">
                  <img
                    className="w-18 h-93"
                    src="./kibrit.svg"
                    alt="kibrit_logo"
                  />
                </a>
              </div>
            </div>
          </footer>

        </div>

      </body>
    </html>
  );
}
