"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useState } from "react";
import { Fragment } from "react";
import { Menu, Transition } from "@headlessui/react";
import { ChevronDownIcon } from "@heroicons/react/20/solid";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function RootLayout({ children }) {
  const [navbar, setNavbar] = useState(false);

  return (
    <html lang="en">
      <body>
        <div className="back">
          <nav className="w-full fixed top-0 left-0 right-0 z-10">
            <div className="justify-between mx-auto lg:max-w-7xl md:items-center md:flex md:px-8">
              <div>
                <div className="flex items-center justify-between py-4 md:py-5 px-4 md:block ">
                  {/* LOGO */}
                  <Link href="/">
                    <div className="text-xs">
                      <img className="w-20 h-93" src="./logo.svg" alt="logo" />
                    </div>
                  </Link>
                  {/* HAMBURGER BUTTON FOR MOBILE */}
                  <div className="md:hidden relative bottom-3">
                    <button
                      className=" text-gray-700 rounded-md outline-none focus:border-gray-400"
                      onClick={() => setNavbar(!navbar)}
                    >
                      {navbar ? (
                        <svg
                          class="h-8 w-8 text-white"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          stroke-width="2"
                          stroke="currentColor"
                          fill="none"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        >
                          {" "}
                          <path stroke="none" d="M0 0h24v24H0z" />{" "}
                          <line x1="18" y1="6" x2="6" y2="18" />{" "}
                          <line x1="6" y1="6" x2="18" y2="18" />
                        </svg>
                      ) : (
                        <svg
                          class="w-5 h-4 text-gray-800 dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 17 14"
                        >
                          <path
                            stroke="currentColor"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M1 1h15M1 7h15M1 13h15"
                          />
                        </svg>
                      )}
                    </button>
                  </div>
                </div>
              </div>

              <div>
                <div
                  className={`flex-1 justify-self-center pb-3 mt-8 md:block md:pb-0 md:mt-0 ${
                    navbar ? "p-12 md:p-0 block" : "hidden"
                  }`}
                >
                  <ul className="h-screen md:h-auto items-center justify-center md:flex ">
                    <li className="pb-6 text-xl text-white py-2 md:px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Help
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Dictionaries
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Menu
                        as="div"
                        className="relative inline-block text-left"
                      >
                        <div>
                          <Menu.Button className="inline-flex w-full justify-center gap-x-1.5 rounded-md py-2 text-xl">
                            Project
                            <ChevronDownIcon
                              className="-mr-1 h-5 w-5 text-[#ff5f53]"
                              aria-hidden="true"
                            />
                          </Menu.Button>
                        </div>

                        <Transition
                          as={Fragment}
                          enter="transition ease-out duration-100"
                          enterFrom="transform opacity-0 scale-95"
                          enterTo="transform opacity-100 scale-100"
                          leave="transition ease-in duration-75"
                          leaveFrom="transform opacity-100 scale-100"
                          leaveTo="transform opacity-0 scale-95"
                        >
                          <Menu.Items className="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                            <div className="py-1">
                              <Menu.Item>
                                {({ active }) => (
                                  <a
                                    href="#"
                                    className={classNames(
                                      active
                                        ? "bg-gray-100 text-gray-900"
                                        : "text-gray-700",
                                      "block px-4 py-2 text-sm"
                                    )}
                                  >
                                    About project
                                  </a>
                                )}
                              </Menu.Item>
                              <Menu.Item>
                                {({ active }) => (
                                  <a
                                    href="#"
                                    className={classNames(
                                      active
                                        ? "bg-gray-100 text-gray-900"
                                        : "text-gray-700",
                                      "block px-4 py-2 text-sm"
                                    )}
                                  >
                                    Thanks
                                  </a>
                                )}
                              </Menu.Item>
                              <Menu.Item>
                                {({ active }) => (
                                  <a
                                    href="#"
                                    className={classNames(
                                      active
                                        ? "bg-gray-100 text-gray-900"
                                        : "text-gray-700",
                                      "block px-4 py-2 text-sm"
                                    )}
                                  >
                                    Participate in project
                                  </a>
                                )}
                              </Menu.Item>
                            </div>
                          </Menu.Items>
                        </Transition>
                      </Menu>
                    </li>

                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Mobile App
                      </Link>
                    </li>
                    <li className="pb-6 text-xl text-white py-2 px-6 text-center">
                      <Link href="#" onClick={() => setNavbar(!navbar)}>
                        Contact us
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>

          {children}

          <footer className="absolute bottom-0 py-5 px-2 w-full">
            <div className="flex justify-between">
              <div className="flex">
                <div>
                  <img
                    className="w-7 h-93"
                    src="./playstore.svg"
                    alt="playstore_logo"
                  />
                </div>
                <div className="pl-8">
                  <img
                    className="w-5 h-93"
                    src="./apple.svg"
                    alt="apple_logo"
                  />
                </div>
              </div>

              <div className="flex">
                <span className="text-white px-3 text-sm">by</span>
                <a href="#">
                  <img
                    className="w-18 h-93"
                    src="./kibrit.svg"
                    alt="kibrit_logo"
                  />
                </a>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
