"use client";

import { Fragment, useState } from 'react'
import { Menu, Transition } from '@headlessui/react'
import { ChevronDownIcon } from '@heroicons/react/20/solid'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Home() {


  return (
    <main className="h-full ">
      <div className="bg-gray-100 h-32 flex flex-col justify-center items-center mx-auto w-2/5 xl:w-1/2 rounded-[3px] ">
        <div className=" p-3 flex items-start relative top-[-16px] w-[100%] ">
          <div className="relative flex items-start h-9 rounded-[3px] bg-white overflow-hidden w-[100%] border-[1px] border-gray-300">
            <div className="grid place-items-start h-full w-12 text-gray-300">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6 absolute top-1 left-1"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </div>

            <input
              className="peer h-full w-full outline-none text-sm text-gray-700 placeholder:text-gray-500 ["
              type="text"
              id="search"
              placeholder="Search"
            />

           

<Menu
                        as="div"
                        className="relative inline-block text-left"
                      >
                        <div>
                          <Menu.Button className="inline-flex w-full justify-center gap-x-1.5 rounded-md py-2 text-sm">
                            En
                            <ChevronDownIcon
                              className="h-4 text-[#ff5f53] mt-2"
                              aria-hidden="true"
                            />
                          </Menu.Button>
                        </div>

                        <Transition
                          as={Fragment}
                          enter="transition ease-out duration-100"
                          enterFrom="transform opacity-0 scale-95"
                          enterTo="transform opacity-100 scale-100"
                          leave="transition ease-in duration-75"
                          leaveFrom="transform opacity-100 scale-100"
                          leaveTo="transform opacity-0 scale-95"
                        >
                          <Menu.Items className="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                            <div className="py-1">
                              <Menu.Item>
                                {({ active }) => (
                                  <a
                                    href="#"
                                    className={classNames(
                                      active
                                        ? "bg-gray-100 text-gray-900"
                                        : "text-gray-700",
                                      "block px-4 py-2 text-sm"
                                    )}
                                  >
                                    Ru
                                  </a>
                                )}
                              </Menu.Item>
                              <Menu.Item>
                                {({ active }) => (
                                  <a
                                    href="#"
                                    className={classNames(
                                      active
                                        ? "bg-gray-100 text-gray-900"
                                        : "text-gray-700",
                                      "block px-4 py-2 text-sm"
                                    )}
                                  >
                                    Az
                                  </a>
                                )}
                              </Menu.Item>
                            </div>
                          </Menu.Items>
                        </Transition>
                      </Menu>


          </div>
        </div>

        <div className="w-[100%] flex px-2 relative top-[-11px]">
          <button className="bg-[#ff5f53] text-white py-1 sm:px-4 rounded-l-[3px] w-[100%]">
            Word-list
          </button>
          <button className="bg-[#475a95] text-white py-1 sm:px-6 rounded-r-[3px] w-[100%]">
            Entries
          </button>
        </div>
      </div>
    </main>
  );
}
